[project]
name = "hyuga"
version = "1.0.0"
description = "Hyuga - Yet Another Hy Language Server"
authors = [{ name = "Yuuta Sakurai", email = "sakurai.yuta@gmail.com" }]
requires-python = ">=3.8,<3.13"
readme = "README.md"
license = "MIT"
dependencies = [
    "hy>=1.0.0,<2",
    "hyrule>=0.7,<0.8",
    "toolz>=0.12.0,<0.13",
    "pygls>=1.2.1,<2",
    "setuptools>=75.2.0,<76",
]

[project.scripts]
hyuga = "hyuga.__main__:main"

[dependency-groups]
dev = ["pytest>=7.1.3,<8"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
