[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
authors = [
    {name = "Yuuta Sakurai", email = "sakurai.yuta@gmail.com"},
]
license = {text = "MIT"}
requires-python = "<3.13,<4.0,>=3.9"
dependencies = [
    "hy>=1.1",
    "hyrule>=1.0",
    "toolz<1.0.0,>=0.12.0",
    "pygls<2.0.0,>=1.2.1",
    "setuptools<76.0.0,>=75.2.0",
]
name = "hyuga"
version = "1.0.0"
description = "Hyuga - Yet Another Hy Language Server"
readme = "README.md"

[project.scripts]
hyuga = "hyuga.__main__:main"

[dependency-groups]
dev = [
    "pytest<8.0.0,>=7.1.3",
]
